/**
 * Pi Image Generation Extension
 *
 * Registers a `generate_image` tool that calls OpenRouter image generation API,
 * saves the result to /tmp, and returns path + metadata to the agent.
 */

import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { Image } from "@mariozechner/pi-tui";
import { reuseOrCreateText } from "@pi-ext/shared";
import { generateImageApi } from "./api";
import { saveImageToTemp } from "./save";

export { generateImageApi } from "./api";
export { saveImageToTemp } from "./save";
export type { GenerateImageApiResult } from "./api";
export type { SaveImageResult } from "./save";

const DEFAULT_MODEL_FAST = "bytedance-research/seedream-4.5";
const DEFAULT_MODEL_BEST = "black-forest-labs/flux-2-max";

interface ExecuteParams {
  prompt: string;
  quality?: "fast" | "best";
  aspect_ratio?: string;
}

export default function (pi: ExtensionAPI): void {
  pi.registerTool({
    name: "generate_image",
    label: "Generate Image",
    description:
      "Generate an image via OpenRouter image generation API. " +
      "Takes a text prompt, optional quality (fast/best) and aspect_ratio, " +
      "returns path + metadata to the agent.",
    parameters: {} as any,

    renderCall(args: any, theme: any, context: any) {
      const quality = args.quality || "fast";
      const text = reuseOrCreateText(context);
      text.setText(
        theme.fg("toolTitle", theme.bold("Generate Image ")) +
          theme.fg("dim", args.prompt) +
          theme.fg("muted", ` [${quality}]`),
      );
      return text;
    },

    renderResult(result: any, _state: any, _theme: any, context: any) {
      const text = reuseOrCreateText(context);
      const d = result.details;
      text.setText(`Generated: ${d.path} (${d.model}, ${d.aspectRatio}, ${d.sizeBytes} bytes)`);
      return text;
    },

    async execute(
      _toolCallId: string,
      params: ExecuteParams,
      _signal: AbortSignal,
      _onUpdate: (update: any) => void,
      ctx: any,
    ) {
      const quality = params.quality || "fast";
      const aspectRatio = params.aspect_ratio || "1:1";
      const model =
        quality === "best"
          ? process.env.IMAGE_MODEL_BEST || DEFAULT_MODEL_BEST
          : process.env.IMAGE_MODEL_FAST || DEFAULT_MODEL_FAST;

      const result = await generateImageApi(params.prompt, model, aspectRatio);

      if (result.images.length === 0) {
        throw new Error("No images generated by the model");
      }

      const image = result.images[0];
      const saved = saveImageToTemp(image.data, image.mimeType);

      // Show image in TUI if available
      if (ctx?.hasUI) {
        await ctx.ui.custom(
          (_tui: any, theme: any, _kb: any, _done: (value?: string) => void) => {
            return new Image(image.data, image.mimeType, theme, {
              maxWidthCells: 80,
              maxHeightCells: 24,
            });
            // Note: image display is dismissed via framework key handling
          },
          { overlay: true },
        );
      }

      return {
        content: [{ type: "text" as const, text: `Generated image saved to ${saved.path}` }],
        details: {
          model,
          aspectRatio,
          sizeBytes: saved.sizeBytes,
          path: saved.path,
        },
      };
    },
  });
}
